name: Deploy Web on Docs Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: npm run build

  deploy:
    name: Deploy to Production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://realgolf.games
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
